### PR TITLE
feat(levm): add new CI directive to show tests result summary

### PR DESCRIPTION
**Pull request by lima-limon-inc**
**Motivation**

In LEVM, every time we need to check how many tests pass, we need to open the `Run tests` directive and scroll all the day down where the Summary section is presented. 
With this patch, a new CI directive called `Show test summary` is created, where only the Summary is shown; thus saving some time.

**Description**

When the CI runs the `make run-evm-ef-tests-ci` directive, it is piped to `tee` which outputs the results to stdout and also a file.
Then, the `Show test summary` directive simply `awk`s said file for the summary.

### CODE REVIEW

**Comment by lima-limon-inc** [comment]
Note: I deleted a comment on LEVM because the CI was only running L1's Actions and not LEVM's (see this commit: https://github.com/lambdaclass/ethrex/pull/1557/commits/1799658590d78235b04e92d7143320aa38a3c4f5).  Thus, I tried changing _something_ to force Github to run LEVM's CI; that comment was the first thing I found. 

Once this is reviewed I will revert the removal of the comment in order to keep the PR "atomic". We can later evaluate why it was running L1's CI instead of LEVM's

**Review by JereSalo — APPROVED** [review]
nice!
do you need to do `tee test_result.txt`?
There is already a file written in `cmd/ef_tests/levm` after executing tests. Can we reuse that file?

**Comment by lima-limon-inc** [comment]
> There is already a file written in `cmd/ef_tests/levm` after executing tests. Can we reuse that file?

Oh, you mean `levm_reports.txt`? I tried using it, the problem I found was that its contents were not deterministic, since it shows only the tests that fail. That means that amount of lines it has changes, and thus there is no easy way to parse it.

Plus, I think its content need some rework. AFAIK, it shows failed tests, so the "Summary:" bit at the beginning always ends up being  "Summary 0/X"

**Comment by JereSalo** [comment]
> > There is already a file written in `cmd/ef_tests/levm` after executing tests. Can we reuse that file?
> 
> Oh, you mean `levm_reports.txt`? I tried using it, the problem I found was that its contents were not deterministic, since it shows only the tests that fail. That means that amount of lines it has changes, and thus there is no easy way to parse it.
> 
> Plus, I think its content need some rework. AFAIK, it shows failed tests, so the "Summary:" bit at the beginning always ends up being "Summary 0/X"

Yeah, my bad. I thought that file had the Summary. It may need a little bit of a rework haha

**Comment by lima-limon-inc** [comment]
> Yeah, my bad. I thought that file had the Summary. It may need a little bit of a rework haha

Haha, no worries! Maybe it's a good task for newcomers? 🤔 

Food for thought

**Pull request merged**
