### PR TITLE
fix(levm): do not transfer value twice to created contracts

### PR DESCRIPTION
**Pull request by ilitteri**
> [!WARNING]
> Depends on #1425 

**Local Run**
```
✓ Summary: 1770/4100 (43.17)

Cancun: 1658/3577 (46.35%)
Shanghai: 57/221 (25.79%)
Homestead: 0/17 (0.00%)
Istanbul: 0/34 (0.00%)
London: 19/39 (48.72%)
Byzantium: 0/33 (0.00%)
Berlin: 17/35 (48.57%)
Constantinople: 0/66 (0.00%)
Merge: 19/62 (30.65%)
Frontier: 0/16 (0.00%)


vmArithmeticTest: 19/19 (100.00%)
stLogTests: 0/46 (0.00%)
stSystemOperationsTest: 25/67 (37.31%)
stCodeCopyTest: 1/2 (50.00%)
stRandom2: 176/220 (80.00%)
stRecursiveCreate: 0/2 (0.00%)
stCodeSizeLimit: 1/5 (20.00%)
stSelfBalance: 3/6 (50.00%)
vmPerformance: 2/2 (100.00%)
stEIP3607: 4/5 (80.00%)
stMemExpandingEIP150Calls: 6/9 (66.67%)
stTransitionTest: 6/6 (100.00%)
stEIP4844-blobtransactions: 4/10 (40.00%)
yul: 5/10 (50.00%)
stSStoreTest: 0/28 (0.00%)
eip6780_selfdestruct: 4/223 (1.79%)
stSolidityTest: 9/18 (50.00%)
eip3855_push0: 14/14 (100.00%)
vmTests: 7/11 (63.64%)
stZeroKnowledge2: 0/130 (0.00%)
stWalletTest: 35/42 (83.33%)
stBugs: 1/4 (25.00%)
stStaticCall: 153/286 (53.50%)
stCreateTest: 5/47 (10.64%)
opcodes: 86/188 (45.74%)
stExtCodeHash: 10/36 (27.78%)
stEIP1559: 9/13 (69.23%)
vmIOandFlowOperations: 10/15 (66.67%)
stReturnDataTest: 27/41 (65.85%)
stRefundTest: 22/22 (100.00%)
stTimeConsuming: 0/14 (0.00%)
stArgsZeroOneBalance: 38/46 (82.61%)
stExample: 7/12 (58.33%)
stAttackTest: 0/2 (0.00%)
stTransactionTest: 21/34 (61.76%)
stRandom: 263/310 (84.84%)
vmBitwiseLogicOperation: 11/11 (100.00%)
eip3651_warm_coinbase: 8/40 (20.00%)
eip2930_access_list: 0/5 (0.00%)
stEIP5656-MCOPY: 2/4 (50.00%)
stShift: 42/42 (100.00%)
eip1344_chainid: 0/6 (0.00%)
eip7516_blobgasfee: 4/5 (80.00%)
stEIP3651-warmcoinbase: 1/2 (50.00%)
stEIP158Specific: 4/8 (50.00%)
eip1153_tstore: 44/67 (65.67%)
stEIP3855-push0: 3/3 (100.00%)
stEIP3860-limitmeterinitcode: 1/3 (33.33%)
stSLoadTest: 1/1 (100.00%)
stCallCodes: 51/79 (64.56%)
stZeroCallsTest: 11/24 (45.83%)
stCallCreateCallCodeTest: 16/43 (37.21%)
stBadOpcode: 2/120 (1.67%)
stPreCompiledContracts: 0/9 (0.00%)
stHomesteadSpecific: 2/5 (40.00%)
stZeroCallsRevert: 4/16 (25.00%)
stEIP150Specific: 9/14 (64.29%)
stEIP2930: 0/7 (0.00%)
stZeroKnowledge: 0/134 (0.00%)
stRevertTest: 18/46 (39.13%)
stChainId: 1/2 (50.00%)
stStaticFlagEnabled: 3/13 (23.08%)
vmLogTest: 5/5 (100.00%)
stInitCodeTest: 3/17 (17.65%)
stEIP150singleCodeGasPrices: 8/40 (20.00%)
stDelegatecallTestHomestead: 14/28 (50.00%)
eip3860_initcode: 52/108 (48.15%)
stSpecialTest: 4/15 (26.67%)
stCallDelegateCodesCallCodeHomestead: 42/58 (72.41%)
stQuadraticComplexityTest: 6/17 (35.29%)
stEIP1153-transientStorage: 0/8 (0.00%)
stMemoryStressTest: 33/38 (86.84%)
stPreCompiledContracts2: 0/102 (0.00%)
stNonZeroCallsTest: 12/24 (50.00%)
eip4844_blobs: 186/559 (33.27%)
eip198_modexp_precompile: 0/144 (0.00%)
stMemoryTest: 66/71 (92.96%)
eip5656_mcopy: 75/93 (80.65%)
stStackTests: 5/10 (50.00%)
stCallDelegateCodesHomestead: 43/58 (74.14%)
stCreate2: 5/51 (9.80%)
```

### CODE REVIEW

**Review by damiramirez — APPROVED** [review]
LGTM

**Review by maximopalopoli — APPROVED** [review]
LGTM

**Review by lima-limon-inc — APPROVED** [review]
LGTM!

Quick question, what do you think about adding a small doc-string on the `msg_value` member for the `CallFrame` struct that explains its purpose? 

From what I've found searching online, `msg_value` has a pretty standard definition. Yet, maybe adding a little comment helps in ensuring that we are all on the same page (Especially for newcomers to the project like myself!).

I was thinking something like this:

`ethrex/crates/vm/levm/src/call_frame.rs`
```rust
pub struct CallFrame {
    (...)
    /// Amount of Wei sent in transaction
    pub msg_value: U256,
    (...)
    pub depth: usize,
}
```

What do you think Ivan?

**Review by JereSalo — APPROVED** [review]
Looks good. I would've created the contract with balance 0 and avoided that `if` statement but it's just a matter of preference. Good catch though, I didn't realize that was causing trouble.

**Comment by ilitteri** [comment]
> Looks good. I would've created the contract with balance 0 and avoided that `if` statement but it's just a matter of preference. Good catch though, I didn't realize that was causing trouble.

Thought the same, but the value needs to be transferred to the contract at its creation in case it needs the balance for some calls. This was a fix introduced by @maximopalopoli.

**Comment by ilitteri** [comment]
> LGTM!
> 
> 
> 
> Quick question, what do you think about adding a small doc-string on the `msg_value` member for the `CallFrame` struct that explains its purpose? 
> 
> 
> 
> From what I've found searching online, `msg_value` has a pretty standard definition. Yet, maybe adding a little comment helps in ensuring that we are all on the same page (Especially for newcomers to the project like myself!).
> 
> 
> 
> I was thinking something like this:
> 
> 
> 
> `ethrex/crates/vm/levm/src/call_frame.rs`
> 
> ```rust
> 
> pub struct CallFrame {
> 
>     (...)
> 
>     /// Amount of Wei sent in transaction
> 
>     pub msg_value: U256,
> 
>     (...)
> 
>     pub depth: usize,
> 
> }
> 
> ```
> 
> 
> 
> What do you think Ivan? 

I agree with you. We can file an issue for adding documentation.

**Pull request merged**
