### PR TITLE
refactor(levm): opcode DupN, LogN and SwapN

### LINKED ISSUE #1428: refactor(levm): opcodes SWAPN, DUPN and LOGN
The implementation could be refactored to something simpler. The N can be a parameter of the generic function.

### PR DESCRIPTION
**Pull request by damiramirez**
**Motivation**

Move opcode logic to an upper layer

**Description**

- Create two functions in `vm.rs` to get the N value
    - `get_n_value()` for `op_push`, `op_dup` and `op_swap`.
    - `get_number_of_topics()` for `op_log`.
    - It's okay to put the function in that file or should I move to other place?
-  Now each opcode expects N (topic, depth or bytes) as a parameter

Closes #1428

### CODE REVIEW

**Review by maximopalopoli — APPROVED** [review]
LGTM

**Review by LeanSerra — APPROVED** [review]
LGTM

**Review by ilitteri — APPROVED** [review]
LGTM. We can merge if more EF tests pass.

**Review by JereSalo — APPROVED** [review]
LGTM

**Pull request merged**
